### ISSUE TITLE
Was there any efforts made to port this extension?

### ISSUE THREAD

**Issue by nikitavoloboev** [flippidippi/sVim#123] opened 2019-08-06 14:18 UTC
I am currently in the process of reading Safari extension docs trying to understand what's needed in order to port this to work on Safari 12.

I am curious if there has been any efforts that were made in this direction? Ideally open source.

**Comment by de-Blaxe** [comment] 2019-08-22 05:26
I'd be interested in helping out. I'm in the process of porting over a similar extension called Vimium.

**Comment by de-Blaxe** [comment] 2019-08-30 23:03
@nikitavoloboev How familiar are you with Swift? I need some help figuring out how to port over the persistent & editable behavior of sVimrc.html

**Comment by nikitavoloboev** [comment] 2019-08-31 11:21
Never wrote much of it. If you share code and what you are trying to do, I can look into it.

**Comment by flippidippi** [comment] 2019-10-11 21:58
Duplicate of https://github.com/flippidippi/sVim/issues/94

**Closed by flippidippi** 2019-10-11 21:58 UTC
