### ISSUE TITLE
Cannot install on Safari 13 in macOS Catalina beta (10.15)

### ISSUE THREAD

**Issue by orthodoX** [flippidippi/sVim#124] opened 2019-08-16 18:41 UTC
I've upgraded to Catalina developer beta and cannot install the extension on Safari 13.

<img width="423" alt="Screenshot 2019-08-16 at 21 39 58" src="https://user-images.githubusercontent.com/370935/63190244-83b31d00-c06e-11e9-85a6-617f92f302f1.png">

Is there any way to install the extension without downgrading the whole OS?

**Comment by ringsaturn** [comment] 2019-08-17 01:44
Maybe we can use this: https://developer.apple.com/documentation/safariservices/safari_app_extensions/converting_a_legacy_safari_extension_to_a_safari_app_extension

**Comment by orthodoX** [comment] 2019-08-17 06:09
@ringsaturn If you/anyone else could do it, I would be more than happy to try it out 😊 
And thanks for a super fast reply!

**Comment by de-Blaxe** [comment] 2019-08-23 03:35
I'd love to start working on porting this over to Safari 12+

**Comment by nikitavoloboev** [comment] 2019-08-23 08:20
I have an empty Safari extension project I created. Was planning to look over at sVim code now to see what logic we should transfer. 

I will push the repo in a bit and maybe we can work on it together? 💚

**Comment by de-Blaxe** [comment] 2019-08-23 08:24
I've got a branch with a few comments. Feel free to check it out.

**Comment by nikitavoloboev** [comment] 2019-08-23 08:25
I see you forked sVim, I thought that it would have to be a total rewrite. 

Checking the code now.

**Comment by de-Blaxe** [comment] 2019-08-23 08:28
I think most of the work will be porting the stuff in the old_html folder to the SwiftExtensionHandler. Most of the javascript should be able to stay. I've only made a few comments at this point though.

**Comment by nikitavoloboev** [comment] 2019-08-23 08:31
Okay I deleted my repo, will try contribute to your branch.

**Comment by orthodoX** [comment] 2019-08-23 09:01
@de-Blaxe @nikitavoloboev Thanks a lot for the effort! Really looking forward to this one 😊

**Comment by mjmarley** [comment] 2019-09-22 03:44
Hi all. Any luck with this now that Safari 13 is official. :(

**Comment by de-Blaxe** [comment] 2019-09-22 04:09
Check out my fork! It’s a work in progress but it’s mostly functional.

**Comment by orthodoX** [comment] 2019-09-22 15:45
@de-Blaxe But how do you install it from your fork? I tried to download the zip of your fork and run the `sVim.safariextz` file, but I'm getting the same error: _Safari doesn't support this extension_...

**Comment by de-Blaxe** [comment] 2019-09-22 17:28
Instructions will be nearly identical to this: https://github.com/televator-apps/vimari/blob/master/docs/safari_12.md

The process is slightly more complicated than the previous one unfortunately.

**Comment by de-Blaxe** [comment] 2019-09-22 17:29
Essentially you’ll be building/signing the Xcode project in the sVimPort folder.

**Comment by Glaciohound** [comment] 2019-10-01 12:29
Thanks for the temporary solution by @de-Blaxe! However it seems a bit tricky for me, as I am still using an old version of Xcode (compatible to my current OSX Sierra) and the project seems to be requiring Swift5 to compile?

Will there be an plug-and-use version in the future?

**Comment by purgat0ri** [comment] 2019-10-06 03:24
I have switched to using Shortcat instead. I hope that it continues to work with Catalina, as the developer has not updated it in some time.

**Comment by de-Blaxe** [comment] 2019-10-06 03:51
@Glaciohound Unfortunately, all extensions have to go through the Mac App Store and I don’t have a developer account for that. There won’t be any easier solutions until I get one. I do plan on reverting the project to swift 4 to make it compatible with older versions of Xcode though

**Comment by translit** [comment] 2019-10-06 06:32
@purgat0ri Try [vimari](https://github.com/televator-apps/vimari). The author is updating it for Catalina, App Store approval is pending.

**Comment by purgat0ri** [comment] 2019-10-06 06:36
> @purgat0ri Try [vimari](https://github.com/televator-apps/vimari). The author is updating it for Catalina, App Store approval is pending.

Many thanks!

**Comment by Glaciohound** [comment] 2019-10-07 07:38
> @Glaciohound Unfortunately, all extensions have to go through the Mac App Store and I don’t have a developer account for that. There won’t be any easier solutions until I get one. I do plan on reverting the project to swift 4 to make it compatible with older versions of Xcode though

Thank you!

**Comment by flippidippi** [comment] 2019-10-11 21:58
Duplicate of https://github.com/flippidippi/sVim/issues/94

**Closed by flippidippi** 2019-10-11 21:58 UTC
